class fraction:

    def __init__(self):
        self.soorat = ""
        self.makhraj = ""


    def show (self):
        ...
    def add (self):
        ...
    def minus (self):
        ...
    def multiplied (self):
        ...
    def power (self):
        ...
    def root (self):
        ...
    def round_off (self):
        ...    
